# Generated by Django 5.0.1 on 2026-02-11 04:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_alter_interview_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='resume_text',
            field=models.TextField(blank=True, help_text='Full resume text for AI question generation'),
        ),
    ]
