# Generated by Django 6.0.2 on 2026-02-14 08:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0006_interview_ai_review_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewShareLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_by_clerk_user_id', models.CharField(blank=True, db_index=True, default='', max_length=200)),
                ('created_by_email', models.EmailField(blank=True, default='', max_length=254)),
                ('role', models.CharField(max_length=200)),
                ('job_description', models.TextField(blank=True, default='')),
                ('experience', models.CharField(blank=True, default='', max_length=200)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='intermediate', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
