# Generated by Django 6.0.2 on 2026-02-14 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0007_interviewsharelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='share_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interview_attempts', to='interviews.interviewsharelink'),
        ),
    ]
